### ISSUE TITLE
How can I change cluster.local?

### ISSUE THREAD

**Issue by defresh** [aerospike/aerospike-kubernetes#16]
I installed aerospike on an in-house kubernetes cluster. I saw the following pod error message.

My Hostname: aerospike-0.aerospike.mynamespace.svc.cluster.local
Hosts in list: aerospike-0.aerospike.mynamespace.svc.mycompany-cluster.com
2020/03/23 21:14:12 aerospike-0.aerospike.mynamespace.svc.mycompany-cluster.com - [10.22.22.22]
2020/03/23 21:14:12 Have not found myself in list yet.

I want to change "cluster.local" to "mycompany-cluster.com".

**Comment by spkesan** [comment]
Hi @defresh 
Thanks for raising this issue. 

At this point, [Aerospike Helm Chart](https://github.com/aerospike/aerospike-kubernetes/tree/master/helm) and [aerospike/aerospike-kubernetes-init](https://github.com/aerospike/aerospike-kubernetes-init) image doesn't support a configurable "service DNS domain". This feature support will be added in the next Helm Chart release.

However, let's try fix your issue with few basic changes (I think you are not using the Helm Chart, but the manifests directly),

1. Add an `install.sh` file to [configs/](https://github.com/aerospike/aerospike-kubernetes/tree/master/configs) directory,

```sh
#! /bin/bash


CONFIG_VOLUME="/etc/aerospike"
NAMESPACE=${POD_NAMESPACE:-default}
K8_SERVICE=${SERVICE:-aerospike}
SERVICE_DNS_DOMAIN=${SERVICE_DNS_DOMAIN:-cluster.local}

for i in "$@"
do
case $i in
    -c=*|--config=*)
    CONFIG_VOLUME="${i#*=}"
    shift
    ;;
    *)
    # unknown option
    ;;
esac
done

echo installing aerospike.conf into "${CONFIG_VOLUME}"
mkdir -p "${CONFIG_VOLUME}"

if [ -f /configs/aerospike.template.conf ]; then
    cp /configs/aerospike.template.conf "${CONFIG_VOLUME}"/
fi

if [ -f /aerospike.sh ]; then
    cp /aerospike.sh "${CONFIG_VOLUME}"/
fi

/peer-finder -on-start=/on-start.sh -service=$K8_SERVICE -ns=${NAMESPACE} -domain=${SERVICE_DNS_DOMAIN}
```

2. Edit [manifests/statefulset.yaml](https://github.com/aerospike/aerospike-kubernetes/blob/master/manifests/statefulset.yaml) and add the following changes (`command`, `args`, `SERVICE_DNS_DOMAIN`),

```yaml
      initContainers:
      - name: aerospike-init
        image: aerospike/aerospike-kubernetes-init:latest
        command: ["/bin/sh"]
        args: ["-c", "cp /configs/install.sh /install.sh && chmod +x /install.sh && /install.sh"]
        volumeMounts:
        - name: confdir
          mountPath: /etc/aerospike
        - name: initconfigs
          mountPath: /configs
        env:    # Variables needed by peer-finder for discovery
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: SERVICE
          value: aerospike
        - name: SERVICE_DNS_DOMAIN
          value: "mycompany-cluster.com"
```

Next, re-deploy the statefulset.

Let me know if that fixes it.
