### ISSUE TITLE
Not able to connect to the Aerospike cluster using k8s ingress

### ISSUE THREAD

**Issue by mmazek** [aerospike/aerospike-kubernetes#31]
Hi, I'm using Aerospike Community installed using the Helm Chart from this repo. I'm deploying to AWS EKS and I'm not able to make it work.
The relevant part of the `values.yaml`:
```
  hostNetwork:
    enabled: true
    useExternalIP: true
  loadBalancerServices:
    enabled: true
```
This way I end up with the following errors printed by the `aerospike-init` container:
```WARN Error getting loadbalancer IP, port and node port: json: cannot unmarshal string into Go struct field ServiceRequest.status of type main.Stat. Retrying.```
After some time the init script finished with Exit status 0 and the pod runs. It's not advertising the external IPs though, so it's not possible to connect from outside of the cluster.
Can you please check this out? Installing Aerospike directly on EC2 is not an option in my case.

Helm Chart version: 5.3.0
`values.yaml`:
```
aerospike:
  dbReplicas: 3
  rbac:
    create: true
    serviceAccountName: aerospike
  hostNetwork:
    enabled: true
    useExternalIP: true
  antiAffinity: "on"
  loadBalancerServices:
    enabled: true
  affinity:
     nodeAffinity:
       requiredDuringSchedulingIgnoredDuringExecution:
         nodeSelectorTerms:
         - matchExpressions:
           - key: topology.kubernetes.io/zone
             operator: In
             values:
             - us-west-2a
  resources:
    requests:
      cpu: 8
      memory: 10Gi
    limits:
      cpu: 10
      memory: 12Gi
  persistenceStorage:
    - mountPath: /opt/aerospike/data-pv
      enabled: true
      name: datadir-pv
      storageClass: ebs-gp3
      accessMode: ReadWriteOnce
      size: 200Gi
      volumeMode: Filesystem

  enableAerospikePrometheusExporter: true
```
