### ISSUE TITLE
Unable to set aerospikeDefaultTTL

### ISSUE THREAD

**Issue by override80** [aerospike/aerospike-kubernetes#35]
Hi! I am trying to set aerospikeDefaultTTL to a generic value (in my case, 1d), but the pods raise the following error during helm upgrade --install aerospike-ce aerospike/aerospike --version 5.5.0 --values aerospike.yaml:

`May 05 2021 14:42:12 GMT: CRITICAL (config): (cfg.c:3082) {test-pjs} must configure non-zero 'nsup-period' or 'allow-ttl-without-nsup' true if 'default-ttl' is non-zero`

aerospike.yaml has the following content:

```
aerospikeNamespace: test-pjs
aerospikeReplicationFactor: 2
dbReplicas: 4
loadBalancerServices:
  enabled: true
  useExternalIP: true
persistenceStorage:
- accessMode: ReadWriteOnce
  devicePath: /dev/sdb
  enabled: true
  name: data-dev
  size: 10Gi
  storageClass: ssd
  volumeMode: Block
```

Looking at the templates it seems to me that we cannot set nsup-period from the values.yaml, am  I missing something?
