### ISSUE TITLE
expose Aerospike cluster 

### ISSUE THREAD

**Issue by afshinpaydar** [aerospike/aerospike-kubernetes#4]
Is there any solution to expose Aerospike Cluster to outside of kubernetes cluster?
By defining service like this, i get below error from outside of kubernetes cluster:

```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: broker
  name: as-cluster-1
  selfLink: /api/v1/namespaces/aerospike-test/services/aerospike
  namespace: aerospike-test
spec:
  externalIPs:
    - 192.168.20.151
    - 192.168.20.152
    - 192.168.20.153
  ports:
    - name: service
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: test
```
```
➜  ~ asadm -h 192.168.20.151
Seed:        [('192.168.20.151', 3000, None)]
Config_file: /root/.aerospike/astools.conf, /etc/aerospike/astools.conf
Aerospike Interactive Shell, version 0.2.0

Found 2 nodes
Online:  192.168.20.151:3000
Offline: 10.130.1.120:3000

Admin> info network
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~Network Information (2019-05-11 03:56:55 UTC)~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
             Node               Node                    Ip       Build   Cluster   Migrations        Cluster     Cluster         Principal   Client     Uptime   
                .                 Id                     .           .      Size            .            Key   Integrity                 .    Conns          .   
10.128.2.245:3000   000000000000000    10.128.2.245:3000     N/E             N/E          N/E   N/E            N/E         N/E                  N/E   N/E        
10.130.1.120:3000   000000000000000    10.130.1.120:3000     N/E             N/E          N/E   N/E            N/E         N/E                  N/E   N/E        
n1.snt.local:3000   *BB97801820A580A   192.168.20.151:3000   C-4.5.2.2         3      0.000     7AF75E1F8C62   True        BB9F502800A580A        3   00:08:09   
Number of rows: 3
```
